#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BoubouDraw.Resource", IsApplication=true)]

namespace BoubouDraw
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int brush = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int circle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int i0 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int i1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int i10 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int i11 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int i12 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int i13 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int i14 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int i2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int i3 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int i4 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int i5 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int i6 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int i7 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int i8 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int i9 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int line = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int rectangle = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int save = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int undo = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int color0 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int color1 = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int color10 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int color11 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int color12 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int color13 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int color14 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int color15 = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int color2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int color3 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int color4 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int color5 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int color6 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int color7 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int color8 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int color9 = 2131099659;
			
			// aapt resource value: 0x7f060024
			public const int drawView = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int hMenu = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int hMenu2 = 2131099666;
			
			// aapt resource value: 0x7f060000
			public const int mainView = 2131099648;
			
			// aapt resource value: 0x7f060022
			public const int save = 2131099682;
			
			// aapt resource value: 0x7f06001e
			public const int shape0 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int shape1 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int shape2 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int shape3 = 2131099681;
			
			// aapt resource value: 0x7f060013
			public const int text0 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int text1 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int text2 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int text3 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int text4 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int text5 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int text6 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int text7 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int text8 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int text9 = 2131099676;
			
			// aapt resource value: 0x7f060023
			public const int undo = 2131099683;
			
			// aapt resource value: 0x7f06001d
			public const int vMenu = 2131099677;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
